name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build release APK and AAB after test
      run: |
         gradle assembleRelease
         gradle bundleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Upload AAB Bundle
      uses: actions/upload-artifact@v2
      with:
         name: app-release.aab
         path: app/build/outputs/bundle/release/app-release.aab
       
